# Generated by Django 4.2.29 on 2026-03-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_plasticentry_inference_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticentry',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plasticentry',
            name='plastic_score',
            field=models.FloatField(default=0.0),
        ),
    ]
