# Generated by Django 3.2.7 on 2026-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticentry',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='annotated_images/'),
        ),
        migrations.AddField(
            model_name='plasticentry',
            name='object_count',
            field=models.IntegerField(default=0),
        ),
    ]
