# Generated by Django 3.2.7 on 2026-03-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20260303_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasticentry',
            name='inference_time',
            field=models.FloatField(default=0.0, help_text='Inference time in ms'),
        ),
    ]
